export const projects = [
  {
    title: "November 7",
    image: "/1.jpeg",
    year: 2024,
    href: "/sample-project",
  },
  {
    title: "March 14",
    image: "/2.jpg",
    year: 2023,
    href: "/sample-project",
  },
  {
    title: "August 23",
    image: "/3.JPG",
    year: 2024,
    href: "/sample-project",
  },
  {
    title: "January 3",
    image: "/4.jpeg",
    year: 2023,
    href: "/sample-project",
  },
  {
    title: "September 18",
    image: "/5.jpeg",
    year: 2024,
    href: "/sample-project",
  },
  {
    title: "December 5",
    image: "/6.JPG",
    year: 2022,
    href: "/sample-project",
  },
  {
    title: "June 29",
    image: "/7.jpeg",
    year: 2024,
    href: "/sample-project",
  },
  {
    title: "February 11",
    image: "/8.jpeg",
    year: 2023,
    href: "/sample-project",
  },
  {
    title: "October 16",
    image: "/9.JPG",
    year: 2024,
    href: "/sample-project",
  },
  {
    title: "May 22",
    image: "/10.JPG",
    year: 2023,
    href: "/sample-project",
  },
  {
    title: "July 8",
    image: "/11.jpeg",
    year: 2022,
    href: "/sample-project",
  },
  {
    title: "April 30",
    image: "/12.jpeg",
    year: 2024,
    href: "/sample-project",
  },
  {
    title: "January 19",
    image: "/13.jpeg",
    year: 2024,
    href: "/sample-project",
  },
  {
    title: "March 26",
    image: "/14.jpeg",
    year: 2023,
    href: "/sample-project",
  },
  {
    title: "August 12",
    image: "/15.JPG",
    year: 2023,
    href: "/sample-project",
  },
  {
    title: "November 25",
    image: "/16.JPG",
    year: 2024,
    href: "/sample-project",
  },
  {
    title: "June 4",
    image: "/17.JPG",
    year: 2023,
    href: "/sample-project",
  },
  {
    title: "September 1",
    image: "/18.jpeg",
    year: 2024,
    href: "/sample-project",
  },
  {
    title: "December 20",
    image: "/19.JPG",
    year: 2023,
    href: "/sample-project",
  },
  {
    title: "February 28",
    image: "/20.jpeg",
    year: 2024,
    href: "/sample-project",
  },
  {
    title: "May 15",
    image: "/21.jpeg",
    year: 2022,
    href: "/sample-project",
  },
  {
    title: "October 9",
    image: "/22.JPG",
    year: 2023,
    href: "/sample-project",
  },
  {
    title: "July 31",
    image: "/23.jpeg",
    year: 2024,
    href: "/sample-project",
  },
  {
    title: "April 6",
    image: "/24.jpeg",
    year: 2022,
    href: "/sample-project",
  },
  {
    title: "August 17",
    image: "/25.JPG",
    year: 2024,
    href: "/sample-project",
  },
];
